Update dotnet.yml
try included gcc?

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -27,25 +27,25 @@ jobs:
       - name: Set up MSBuild
         uses: microsoft/setup-msbuild@v2
       
-      - name: Install TDM-GCC
-        run: |
-          $fileUrl = "https://github.com/jmeubank/tdm-gcc-src/releases/download/v10.3.0-tdm64-1/gcc-10.3.0-tdm64-1-core.zip"
-          $zipPath = "$env:TEMP\gcc-10.3.0-tdm64-1-core.zip"
-          $extractPath = "C:\TDM-GCC-64"
-          
-          Invoke-WebRequest -Uri $fileUrl -OutFile $zipPath
-          if (-Not (Test-Path $zipPath)) {
-            Write-Error "Failed to download TDM-GCC ZIP file"
-            exit 1
-          }
+      # - name: Install TDM-GCC
+        # run: |
+        #  $fileUrl = "https://github.com/jmeubank/tdm-gcc-src/releases/download/v10.3.0-tdm64-1/gcc-10.3.0-tdm64-1-core.zip"
+        #  $zipPath = "$env:TEMP\gcc-10.3.0-tdm64-1-core.zip"
+        #  $extractPath = "C:\TDM-GCC-64"
+        #  
+        #  Invoke-WebRequest -Uri $fileUrl -OutFile $zipPath
+        #  if (-Not (Test-Path $zipPath)) {
+        #    Write-Error "Failed to download TDM-GCC ZIP file"
+        #    exit 1
+        #  }
 
-          Write-Host "Extracting TDM-GCC..."
-          Expand-Archive -Path $zipPath -DestinationPath $extractPath
+        #  Write-Host "Extracting TDM-GCC..."
+        #  Expand-Archive -Path $zipPath -DestinationPath $extractPath
 
-          $env:Path += ";$extractPath\bin;$extractPath\lib"
+        #  $env:Path += ";$extractPath\bin;$extractPath\lib"
 
-          Write-Host "TDM-GCC installed successfully"
-          gcc.exe --version
+        #  Write-Host "TDM-GCC installed successfully"
+        #  gcc.exe --version
 
       - name: Restore NuGet packages
         run: |
